# Generated by Django 3.0.7 on 2020-06-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_user',
            name='registration_year',
            field=models.PositiveSmallIntegerField(help_text='YYYY format'),
        ),
    ]
